// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateCurrencyInput struct {
	Code        string  `json:"code"`
	Name        string  `json:"name"`
	MarketValue float64 `json:"marketValue"`
}

type CreatePortfolioInput struct {
	UserEmail string  `json:"userEmail"`
	Name      *string `json:"name"`
}

type CreateTransactionInput struct {
	PorfolioID   string  `json:"porfolioID"`
	PricePerCoin float64 `json:"pricePerCoin"`
	Quantity     float64 `json:"quantity"`
	CurrencyCode string  `json:"currencyCode"`
}

type CreateUserInput struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
}
