// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreatePortfolioInput struct {
	User         string  `json:"user"`
	FiatCurrency string  `json:"fiatCurrency"`
	Name         *string `json:"name"`
}

type CreateUserInput struct {
	Email string `json:"email"`
	Name  string `json:"name"`
}
