// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateCurrencyInput struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

type CreateUserInput struct {
	Email string `json:"email"`
	Name  string `json:"name"`
}

type Currency struct {
	ID   string `json:"id"`
	Code string `json:"code"`
	Name string `json:"name"`
}

type Portfolio struct {
	ID           string    `json:"id"`
	Name         *string   `json:"name"`
	FiatCurrency *Currency `json:"fiatCurrency"`
	User         *User     `json:"user"`
}

type User struct {
	ID         string       `json:"id"`
	Email      string       `json:"email"`
	Name       string       `json:"name"`
	Portfolios []*Portfolio `json:"portfolios"`
}
